version: "3"
services:
  php:
    build: ./php
    container_name: php
    expose:
      - 9000
    volumes:
      - ./html:/var/www/html

  nginx:
    build: ./nginx
    container_name: nginx
    ports:
      - 8080:80
    volumes:
      - ./html:/var/www/html
    depends_on:
      - php  

  mysql:
      image: mysql:8.1.0
      container_name: mysql
      environment:
        MYSQL_ROOT_PASSWORD: root_password
        MYSQL_DATABASE: test
      volumes:
        - ./html:/var/www/html
        - ./dbdata:/var/lib/mysql
volumes:
  dbdata:
